=== AlbertoAguado/ACTIVIDAD_2/biblioteca.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="biblioteca">
         <xs:complexType>
            <xs:sequence>
                <!-- LIBRO -->
                <xs:element name="libro">
                     <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo_libro" type=" xs:string"></xs:element>
                            <xs:element name="capitulos" minOccurs="0">
                                 <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                                             <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo_capitulo" type="xs:string"></xs:element>
                                                    <xs:element name="contenido_capitulo" type="xs:string"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="paginas" type="xs:integer" use="required"></xs:attribute>
                                             </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                 </xs:complexType>
                            </xs:element>
                            <xs:element name="indice_libro" type=" xs:string" minOccurs="0"></xs:element>
                            <xs:element name="sinopsis" type=" xs:string"></xs:element>
                        </xs:sequence>
                         <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="L([0-9]){4}" />
                                </xs:restriction>
                            </xs:simpleType>
                         </xs:attribute>
                         <xs:attribute name="tipo_clase" type=" xs:string" use="required"> </xs:attribute>
                         <xs:attribute name="paginas" type=" xs:integer" use="required"> </xs:attribute>
                     </xs:complexType> 
                </xs:element>

                <!-- REVISTA -->
                <xs:element name="revista">
                     <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo_revista" type=" xs:string"></xs:element>
                            <xs:element name="numero" type="xs:integer"></xs:element>
                            <xs:element name="indice_revista"></xs:element>
                            <xs:element name="secciones_revista">
                                 <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="seccion_revista" minOccurs="1" maxOccurs="unbounded">
                                             <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="contenido_seccion" type=" xs:string"></xs:element>
                                                </xs:sequence>
                                                 <xs:attribute name="paginas" type=" xs:integer" use="required"> </xs:attribute>
                                             </xs:complexType>  
                                        </xs:element>
                                    </xs:sequence>
                                 </xs:complexType>  
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="R([0-9]){4}" />
                                </xs:restriction>
                            </xs:simpleType>
                         </xs:attribute>
                         <xs:attribute name="tipo_clase" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="informatica"/>
                                    <xs:enumeration value="corazon"/>
                                    <xs:enumeration value="coches"/>
                                    <xs:enumeration value="investigacion"/>
                                    <xs:enumeration value="otras"/>
                                </xs:restriction>
                            </xs:simpleType>
                         </xs:attribute>
                         <xs:attribute name="paginas" type=" xs:integer" use="required"> </xs:attribute>
                     </xs:complexType>  
                </xs:element>

                <!-- PERIODICO -->
                <xs:element name="periodico">
                     <xs:complexType>
                        <xs:sequence>
                            <xs:element name="secciones_periodico">
                                 <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="seccion_periodico" minOccurs="1" maxOccurs="unbounded">
                                             <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="articulo" minOccurs="1" maxOccurs="unbounded">
                                                         <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="contenido_articulo"></xs:element>
                                                                </xs:sequence>
                                                                 <xs:attribute name="autor" type=" xs:string" use="required"> </xs:attribute>
                                                             </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="tipo" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="economica"/>
                                                            <xs:enumeration value="opinion"/>
                                                            <xs:enumeration value="deportes"/>
                                                            <xs:enumeration value="nacional"/>
                                                            <xs:enumeration value="internacional"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                             </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                 </xs:complexType>
                            </xs:element>
                            <xs:element name="indice_periodico" type=" xs:string">
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="P([0-9]){4}" />
                                </xs:restriction>
                            </xs:simpleType>
                         </xs:attribute>
                         <xs:attribute name="tipo_clase" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="nacional"/>
                                    <xs:enumeration value="internacional"/>
                                </xs:restriction>
                            </xs:simpleType>
                         </xs:attribute>
                         <xs:attribute name="fecha_de_publicacion" type="xs:date" use="required"></xs:attribute>
                     </xs:complexType>
                </xs:element>
            </xs:sequence>
         </xs:complexType>
    </xs:element>
</xs:schema>

=== AlbertoAguado/ACTIVIDAD_2/biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<!DOCTYPE biblioteca []>-->
<!--<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">-->

<!--Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos. Todos los documentos están identificados por el atributo Id.
Para los libros este atributo empieza con la letra “L” seguido de 4 dígitos identificativos.
Para los periódicos este atributo empieza por la letra “P” seguido de los 4 dígitos identificativos.
En el caso de las revistas empieza por la letra “R”. -->

<!--Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo identificativo de su clase denominado tipo_clase. Dentro de cada libro se tiene un título, varios capítulos con el título en su interior, un índice y una sinopsis. Tanto en libro como en capítulo existe un atributo que contiene el número de páginas del libro o del capítulo, según corresponda. Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a la información.  -->

<!--Las revistas a su vez son clasificadas en: informática, corazón, coches, investigación y otras. Cada revista tiene el atributo tipo_clase identificativo de la clase a la que pertenece. Dentro de cada revista tenemos el título, el número de la revista, un índice de contenido y las secciones. En cada sección y en la revista se tiene un atributo que contiene el número de páginas. Además, en cada sección se tiene la parte denominada contenido, en la que se tiene un atributo con un enlace a la información. De igual forma que en los anteriores, la última etiqueta del árbol debe ser el contenido con un atributo que referencia al contenido.-->

<!--Los periódicos se clasifican en nacionales e internacionales. Cada periódico contiene el atributo tipo_clase identificativo de la clase a la que pertenece y un atributo que incluye la fecha de publicación.
Dentro de los periódicos tenemos secciones y un índice. Cada sección debe contener un atributo identificativo del tipo de sección, que puede ser: económica, opinión, deportes, nacional o internacional. Las secciones se dividen en artículos, en donde se define en un atributo el autor. Finalmente, el contenido será el último elemento del árbol, que necesita un atributo que referencie a la información. -->

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "biblioteca.xsd">
    <libro id="L5646" tipo_clase="didactico" paginas="639">
        <titulo_libro>
            Una breve historia de casi todo
        </titulo_libro>
        
        <capitulos>
            <capitulo paginas="63">
                <titulo_capitulo>Perdidos en el Cosmos</titulo_capitulo>
                <contenido_capitulo></contenido_capitulo>
            </capitulo>
            <capitulo paginas="61">
                <titulo_capitulo>El tamaño de la Tierra</titulo_capitulo>
                <contenido_capitulo></contenido_capitulo>
            </capitulo>
            <capitulo paginas="88">
                <titulo_capitulo>Nace una nueva era</titulo_capitulo>
                <contenido_capitulo></contenido_capitulo>
            </capitulo>
            <capitulo paginas="41">
                <titulo_capitulo>Un planeta peligroso</titulo_capitulo>
                <contenido_capitulo></contenido_capitulo>
            </capitulo>
            <capitulo paginas="197">
                <titulo_capitulo>La vida misma</titulo_capitulo>
                <contenido_capitulo></contenido_capitulo>
            </capitulo>
            <capitulo paginas="58">
                <titulo_capitulo>El camino hasta nosotros</titulo_capitulo>
                <contenido_capitulo></contenido_capitulo>
            </capitulo>
        </capitulos>
        
        <indice_libro>
            2.1	Capítulo I: Perdidos en el cosmos
            2.1.1	1. Cómo construir un universo
            2.1.2	2. Bienvenido al sistema solar
            2.1.3	3. El universo del Reverendo Evans
            2.2	Capítulo II: El tamaño de la tierra
            2.2.1	4. La medida de las cosas
            2.2.2	5. Los coleccionistas de rocas
            2.2.3	6. Grandes y sangrientas batallas científicas
            2.2.4	7. Cuestiones elementales
            2.3	Capítulo III: Nace una nueva era
            2.3.1	8. El universo de Einstein
            2.3.2	9. El poderoso átomo
            2.3.3	10. El plomo, los clorofluorocarbonos y la edad de la Tierra
            2.3.4	11. Los quarks en Munster Mark
            2.3.5	12. La Tierra se mueve
            2.4	Capítulo IV: Un planeta peligroso
            2.4.1	13. ¡Bang!
            2.4.2	14. El fuego de abajo
            2.4.3	15. La belleza peligrosa
            2.5	Capítulo V: La vida misma
            2.5.1	16. Un planeta solitario
            2.5.2	17. En la Troposfera
            2.5.3	18. El mar delimitador
            2.5.4	19. La aparición de la vida
            2.5.5	20. Un mundo pequeño
            2.5.6	21. La vida sigue
            2.5.7	22. Adiós a todo eso
            2.5.8	23. La riqueza del ser
            2.5.9	24. Células
            2.5.10	25. La idea singular de Darwin
            2.5.11	26. El material de la vida
            2.6	Capítulo VI: El camino hasta nosotros
            2.6.1	27. Tiempo de hielo
            2.6.2	28. El bípedo misterioso
            2.6.3	29. El mono inquieto
            2.6.4	30. Adiós
        </indice_libro>

        <sinopsis>
            ¿Puede un solo libro convertirse en la perfecta introducción para adentrarse en disciplinas tan dispares como la astronomía, la geología, la física, la química y la biología? ¿Puede un trabajo de divulgación científica ofrecer razonamientos y datos precisos, y al mismo tiempo ser tremendamente entretenido? ¿Puede una única obra narrar la historia de los grandes descubrimientos de la ciencia y contarnos también divertidas anécdotas relacionadas con estos extraordinarios logros? Con Una breve historia de casi todo, Bill Bryson nos propone un fascinante recorrido por la historia del universo que nos rodea y los conocimientos que nos han llevado a comprenderlo un poco mejor.
        </sinopsis>
    </libro>

    <revista id="R4568" tipo_clase="informatica" paginas="154">
        <titulo_revista>
            Computer hoy
        </titulo_revista>

        <numero>
            1236
        </numero>

        <indice_revista>

        </indice_revista>

        <secciones_revista>
            <seccion_revista paginas="16">
                <contenido_seccion>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi culpa minima porro totam deleniti. Molestiae perspiciatis atque excepturi consequuntur quo id debitis quod autem, illum adipisci facilis eveniet ab cupiditate?
                </contenido_seccion>
            </seccion_revista>
            <seccion_revista paginas="20">
                <contenido_seccion>
                    Recusandae voluptatum et quo atque laudantium voluptas nulla enim adipisci sunt natus? Nostrum cupiditate qui deleniti et ipsum eum reiciendis aperiam quod soluta labore? Maxime dicta necessitatibus sit excepturi odio?
                </contenido_seccion>
            </seccion_revista>
            <seccion_revista paginas="12">
                <contenido_seccion>
                    Ut accusantium reprehenderit magni fugiat possimus repellendus excepturi eveniet quam quibusdam odio obcaecati voluptatem mollitia corrupti, dicta vitae, nemo quo ullam ducimus cum laboriosam nihil laudantium? Odit laudantium nemo pariatur.
                </contenido_seccion>
            </seccion_revista>
        </secciones_revista>
    </revista>

    <periodico id="P4578" tipo_clase="nacional" fecha_de_publicacion="2021-05-13">
        <secciones_periodico>
            <seccion_periodico tipo="internacional">
                <articulo autor="">
                    <contenido_articulo></contenido_articulo>
                </articulo>
                <articulo autor="">
                    <contenido_articulo></contenido_articulo>
                </articulo>
            </seccion_periodico>
        </secciones_periodico>
        <indice_periodico>

        </indice_periodico>
    </periodico>
</biblioteca>
